# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git init
    git clone https://github.com/emscripten-core/emsdk.git
    ./emsdk/emsdk install latest
    ./emsdk/emsdk activate latest
    source ./emsdk/emsdk_env.sh
    npm install
    npm run test
  displayName: 'npm install and build'
